import pandas as pd
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
# from typing import Dict, Any, List

# This is a conceptual BI Analyzer. Real-world BI analysis can be very complex,
# involving statistical modeling, data visualization generation, etc.
# This example focuses on using an LLM to interpret data and generate insights based on prompts.

class BIAnalyzer:
    def __init__(self, llm: ChatOpenAI):
        """
        Initializes the BIAnalyzer with a ChatOpenAI language model.

        Args:
            llm (ChatOpenAI): An instance of the ChatOpenAI language model.
        """
        self.llm = llm

        # A generic prompt for generating insights from a DataFrame summary and a user query.
        # This can be expanded with more specific prompts for different analysis types.
        insights_prompt_template = """
        You are a Business Intelligence Analyst.
        Given the following data summary and a user query, provide concise insights.
        Focus on answering the query and highlighting key trends or patterns relevant to it.

        Data Summary:
        {data_summary}

        User Query: "{user_query}"

        Key Insights:
        1.
        2.
        3.
        ...
        (Provide a few bullet points if possible, or a short paragraph)
        """
        self.insights_prompt = PromptTemplate(
            input_variables=["data_summary", "user_query"],
            template=insights_prompt_template,
        )
        self.insights_chain = LLMChain(llm=self.llm, prompt=self.insights_prompt)

        # Prompt for suggesting follow-up questions
        follow_up_prompt_template = """
        You are a helpful BI assistant. Based on the provided data summary and the initial query,
        suggest 2-3 insightful follow-up questions that the user might be interested in.

        Data Summary (first few rows and column descriptions):
        {data_summary}

        Initial User Query: "{user_query}"

        Suggested Follow-up Questions (be concise and relevant):
        1.
        2.
        3.
        """
        self.follow_up_prompt = PromptTemplate(
            input_variables=["data_summary", "user_query"],
            template=follow_up_prompt_template
        )
        self.follow_up_chain = LLMChain(llm=self.llm, prompt=self.follow_up_prompt)


    def generate_data_summary(self, df: pd.DataFrame, max_rows_to_show: int = 5) -> str:
        """
        Generates a textual summary of a DataFrame.

        Args:
            df (pd.DataFrame): The DataFrame to summarize.
            max_rows_to_show (int): Max number of rows to include in the head/sample.

        Returns:
            str: A string containing the summary (shape, columns, head, describe).
        """
        if df is None or df.empty:
            return "The DataFrame is empty or not loaded."

        summary = []
        summary.append(f"Shape: {df.shape}")
        summary.append(f"\nColumns and Data Types:\n{df.dtypes.to_string()}")

        # Basic statistics for numerical columns
        if not df.select_dtypes(include='number').empty:
            summary.append(f"\nDescriptive Statistics (Numerical):\n{df.describe().to_string()}")
        else:
            summary.append("\nDescriptive Statistics (Numerical): No numerical data to describe.")

        # Basic statistics for object/categorical columns
        if not df.select_dtypes(include='object').empty:
             summary.append(f"\nDescriptive Statistics (Categorical):\n{df.describe(include='object').to_string()}")
        else:
            summary.append("\nDescriptive Statistics (Categorical): No categorical data to describe.")

        summary.append(f"\nFirst {max_rows_to_show} rows:\n{df.head(max_rows_to_show).to_string()}")

        return "\n".join(summary)

    def get_insights(self, df: pd.DataFrame, user_query: str) -> str:
        """
        Generates BI insights based on the DataFrame and a user query.

        Args:
            df (pd.DataFrame): The DataFrame for analysis.
            user_query (str): The user's query or area of interest.

        Returns:
            str: Textual insights generated by the LLM.
        """
        if df is None or df.empty:
            return "Cannot generate insights: DataFrame is empty or not loaded."
        if not user_query:
            return "Cannot generate insights: User query is empty."

        data_summary = self.generate_data_summary(df, max_rows_to_show=3) # Keep summary for prompt concise

        try:
            response = self.insights_chain.invoke({
                "data_summary": data_summary,
                "user_query": user_query
            })
            return response.get('text', "Could not generate insights at this time.").strip()
        except Exception as e:
            print(f"Error generating insights: {e}")
            return f"Error: Could not process the request for insights. Details: {e}"

    def suggest_follow_up_questions(self, df: pd.DataFrame, initial_query: str) -> str:
        """
        Suggests follow-up questions based on the data and initial query.

        Args:
            df (pd.DataFrame): The DataFrame being analyzed.
            initial_query (str): The user's initial query.

        Returns:
            str: A string containing suggested follow-up questions.
        """
        if df is None or df.empty:
            return "Cannot suggest questions: DataFrame is empty or not loaded."

        # A more concise summary for this prompt
        concise_summary = []
        concise_summary.append(f"Columns: {', '.join(df.columns.tolist())}")
        concise_summary.append(f"\nFirst few rows:\n{df.head(2).to_string()}")

        try:
            response = self.follow_up_chain.invoke({
                "data_summary": "\n".join(concise_summary),
                "user_query": initial_query
            })
            return response.get('text', "Could not generate follow-up questions.").strip()
        except Exception as e:
            print(f"Error suggesting follow-up questions: {e}")
            return f"Error: Could not suggest follow-up questions. Details: {e}"


# Example Usage (for testing)
if __name__ == '__main__':
    import os
    from dotenv import load_dotenv
    # Adjust path to .env: it should be in the root of chatbot_local_bi directory
    dotenv_path = os.path.join(os.path.dirname(__file__), '..', '..', '.env')
    load_dotenv(dotenv_path=dotenv_path)

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("Please set the OPENAI_API_KEY environment variable to run this example.")
    else:
        chat_model = ChatOpenAI(api_key=api_key, model_name="gpt-3.5-turbo", temperature=0.2)
        analyzer = BIAnalyzer(llm=chat_model)

        # Sample DataFrame
        data = {
            'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Clothing', 'Electronics'],
            'Sales': [15000, 8000, 12000, 5000, 9000, 18000],
            'Region': ['North', 'South', 'North', 'East', 'West', 'North'],
            'CustomerSatisfaction': [4, 3, 5, 4, 2, 5] # Scale of 1-5
        }
        sample_df = pd.DataFrame(data)

        print("--- Data Summary ---")
        summary = analyzer.generate_data_summary(sample_df)
        print(summary)

        print("\n--- Generating Insights ---")
        query1 = "What are the key sales trends by product category in the North region?"
        insights1 = analyzer.get_insights(sample_df, query1)
        print(f"Query: {query1}\nInsights:\n{insights1}")

        query2 = "How does customer satisfaction relate to sales?"
        insights2 = analyzer.get_insights(sample_df, query2)
        print(f"\nQuery: {query2}\nInsights:\n{insights2}")

        print("\n--- Suggesting Follow-up Questions ---")
        follow_ups = analyzer.suggest_follow_up_questions(sample_df, query1)
        print(f"Based on query '{query1}', suggested follow-ups:\n{follow_ups}")

        # Test with empty DataFrame
        empty_df = pd.DataFrame()
        print("\n--- Test with Empty DataFrame ---")
        print(analyzer.get_insights(empty_df, "Any insights?"))
        print(analyzer.suggest_follow_up_questions(empty_df, "Any questions?"))
