import pandas as pd
from langchain_openai import BaseOpenAI # Using BaseOpenAI for broader compatibility if needed, or ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from datetime import datetime
# from weasyprint import HTML # Example for PDF generation from HTML, requires 'pip install weasyprint'
# from io import BytesIO

# This is a conceptual ReportGenerator. Actual report generation can involve
# complex templating, data visualization embedding, and various output formats.

class ReportGenerator:
    def __init__(self, llm: BaseOpenAI): # Or ChatOpenAI
        """
        Initializes the ReportGenerator with a language model.

        Args:
            llm (BaseOpenAI | ChatOpenAI): An instance of an OpenAI language model.
        """
        self.llm = llm

        # Prompt for generating a textual summary report based on insights.
        report_prompt_template = """
        You are a Report Writing Assistant.
        Based on the provided title, data summary, and key insights, generate a concise textual report.
        The report should be well-structured with an introduction, main findings based on insights,
        and a brief conclusion.

        Report Title: "{report_title}"

        Data Summary (optional, for context):
        {data_summary}

        Key Insights to Incorporate:
        {key_insights}

        Generated Report:
        """
        self.report_prompt = PromptTemplate(
            input_variables=["report_title", "data_summary", "key_insights"],
            template=report_prompt_template,
        )
        self.report_chain = LLMChain(llm=self.llm, prompt=self.report_prompt)

    def _get_default_report_title(self) -> str:
        """Generates a default report title with a timestamp."""
        return f"Analysis Report - {datetime.now().strftime('%Y-%m-%d %H:%M')}"

    def generate_text_report(self,
                             key_insights: str,
                             data_summary: str = None,
                             report_title: str = None) -> str:
        """
        Generates a textual report based on key insights and optional data summary.

        Args:
            key_insights (str): The core findings or insights to be included in the report.
            data_summary (str, optional): A summary of the data used for context.
                                          Can be generated by BIAnalyzer.generate_data_summary().
            report_title (str, optional): The title for the report. A default will be used if None.

        Returns:
            str: The generated textual report.
        """
        if not key_insights:
            return "Error: Key insights are required to generate a report."

        if report_title is None:
            report_title = self._get_default_report_title()

        # Provide a default for data_summary if not given, to avoid issues with the prompt
        data_summary_for_prompt = data_summary if data_summary else "Not provided."

        try:
            response = self.report_chain.invoke({
                "report_title": report_title,
                "data_summary": data_summary_for_prompt,
                "key_insights": key_insights
            })
            return response.get('text', f"Could not generate report for '{report_title}'.").strip()
        except Exception as e:
            print(f"Error generating text report: {e}")
            return f"Error: Could not process the request for report generation. Details: {e}"

    def generate_html_report(self,
                             key_insights: str,
                             df_preview: pd.DataFrame = None,
                             report_title: str = None,
                             custom_intro: str = None) -> str:
        """
        Generates a simple HTML report.

        Args:
            key_insights (str): Key insights text (can be multi-line).
            df_preview (pd.DataFrame, optional): DataFrame to include as an HTML table preview.
            report_title (str, optional): Title of the report.
            custom_intro (str, optional): A custom introduction paragraph.

        Returns:
            str: HTML string representing the report.
        """
        if report_title is None:
            report_title = self._get_default_report_title()

        insights_html = "<p>" + key_insights.replace("\n", "<br>") + "</p>"
        df_html = df_preview.to_html(max_rows=10, border=1) if df_preview is not None and not df_preview.empty else "<p>No data preview available.</p>"
        intro_html = f"<p>{custom_intro}</p>" if custom_intro else "<p>This report summarizes the key findings from the data analysis.</p>"

        html_content = f"""
        <html>
        <head>
            <title>{report_title}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                h1 {{ color: #333; }}
                h2 {{ color: #555; }}
                table {{ border-collapse: collapse; width: auto; margin-top: 15px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; }}
                .insights {{ background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin-top:15px;}}
            </style>
        </head>
        <body>
            <h1>{report_title}</h1>
            {intro_html}

            <h2>Key Insights</h2>
            <div class="insights">
                {insights_html}
            </div>

            <h2>Data Preview</h2>
            {df_html}

            <p style="font-size:0.8em; color:grey; margin-top:20px;">Report generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </body>
        </html>
        """
        return html_content.strip()

    # def generate_pdf_report(self, html_content: str) -> (BytesIO | str):
    #     """
    #     Converts HTML content to a PDF file in memory.
    #     Requires WeasyPrint: pip install weasyprint
    #
    #     Args:
    #         html_content (str): HTML string to convert.
    #
    #     Returns:
    #         BytesIO: A BytesIO stream containing the PDF data, or an error string.
    #     """
    #     if 'HTML' not in globals():
    #         return ("Error: WeasyPrint library not installed. "
    #                 "Cannot generate PDF. Please install with 'pip install weasyprint'.")
    #     try:
    #         pdf_buffer = BytesIO()
    #         HTML(string=html_content).write_pdf(pdf_buffer)
    #         pdf_buffer.seek(0)
    #         return pdf_buffer
    #     except Exception as e:
    #         print(f"Error generating PDF report: {e}")
    #         return f"Error: Could not generate PDF. Details: {e}"


# Example Usage (for testing)
if __name__ == '__main__':
    import os
    from dotenv import load_dotenv
    from langchain_openai import OpenAI # Using OpenAI for this example

    dotenv_path = os.path.join(os.path.dirname(__file__), '..', '..', '.env')
    load_dotenv(dotenv_path=dotenv_path)

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("Please set the OPENAI_API_KEY environment variable to run this example.")
    else:
        # Use the base OpenAI for the LLMChain in this example
        llm_instance = OpenAI(api_key=api_key, temperature=0.2)
        report_gen = ReportGenerator(llm=llm_instance)

        sample_insights = """
        - Sales have increased by 15% in the last quarter, driven by the new marketing campaign.
        - The 'Gadgets' category shows the highest profit margin at 25%.
        - Customer satisfaction in the 'Services' sector needs improvement, currently averaging 3.5/5 stars.
        - Regional performance varies, with the North region outperforming others by 10%.
        """
        sample_data_summary = """
        Dataset: Sales Data Q3 2023
        Total Records: 1,500
        Key Columns: ProductID, SaleAmount, Region, CustomerRating
        Date Range: 2023-07-01 to 2023-09-30
        """

        # Sample DataFrame for HTML report
        df_data = {
            'Product': ['Alpha', 'Beta', 'Gamma'],
            'Sales Q3': [1200, 1500, 900],
            'Region': ['North', 'North', 'South']
        }
        sample_df = pd.DataFrame(df_data)

        print("--- Generating Text Report (LLM based) ---")
        text_report = report_gen.generate_text_report(
            key_insights=sample_insights,
            data_summary=sample_data_summary,
            report_title="Quarterly Sales Performance Review"
        )
        print(text_report)

        print("\n\n--- Generating HTML Report ---")
        html_report = report_gen.generate_html_report(
            key_insights=sample_insights,
            df_preview=sample_df,
            report_title="Interactive Sales Dashboard Insights - Q3",
            custom_intro="This document provides a summary of sales activities and key performance indicators for the third quarter."
        )
        print(f"HTML Report (first 200 chars):\n{html_report[:200]}...")

        # To save and view the HTML report:
        html_file_path = "sample_report.html"
        with open(html_file_path, "w", encoding="utf-8") as f:
            f.write(html_report)
        print(f"\nHTML report saved to: {os.path.abspath(html_file_path)}")

        # Example for PDF generation (if WeasyPrint was enabled and installed)
        # print("\n\n--- Generating PDF Report (from HTML) ---")
        # pdf_result = report_gen.generate_pdf_report(html_report)
        # if isinstance(pdf_result, BytesIO):
        #     pdf_file_path = "sample_report.pdf"
        #     with open(pdf_file_path, "wb") as f:
        #         f.write(pdf_result.getvalue())
        #     print(f"PDF report saved to: {os.path.abspath(pdf_file_path)}")
        # else:
        #     print(pdf_result) # Print error message

        # if os.path.exists(html_file_path):
        #     os.remove(html_file_path)
        # if 'pdf_file_path' in locals() and os.path.exists(pdf_file_path):
        #    os.remove(pdf_file_path)
